server:
  port: 8185

springfox:
  documentation:
    swagger:
      v2:
        enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/wpz
    username: wpz_user
    password: wpz_password


jwt.secret: very-very-secret-key-should-be-almost-infinity
jwt.expiration: 86400
